[config]
# Sets the default theme styling (choices: 'dark' or 'light')
mode = "dark"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar-colors.css"
output_path = "~/.config/waybar/themes/colors.css"
post_hook = 'pkill -SIGUSR2 waybar'
