[config]

[templates.swaync]
input_path = "~/.config/matugen/templates/swaync-colors.css"
output_path = "~/.config/swaync/themes/colors.css"
post_hook = "swaync-client -rs"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar-colors.css"
output_path = "~/.config/waybar/themes/colors.css"
post_hook = 'pkill -SIGUSR2 waybar'

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.lua"
output_path = '~/.config/hypr/colors.lua' 

[templates.fuzzel]
input_path = "~/.config/matugen/templates/fuzzel-colors.ini"
output_path = '~/.config/fuzzel/colors.ini'

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = '~/.config/matugen/post-hook-scripts/gtk-themes-reload.sh'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'
